package com.mybatis.bean;

public class Person {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_person.id
     *
     * @mbg.generated Fri Jul 30 21:34:44 GMT+08:00 2021
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_person.name
     *
     * @mbg.generated Fri Jul 30 21:34:44 GMT+08:00 2021
     */
    private String name;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_person.id
     *
     * @return the value of t_person.id
     *
     * @mbg.generated Fri Jul 30 21:34:44 GMT+08:00 2021
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_person.id
     *
     * @param id the value for t_person.id
     *
     * @mbg.generated Fri Jul 30 21:34:44 GMT+08:00 2021
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_person.name
     *
     * @return the value of t_person.name
     *
     * @mbg.generated Fri Jul 30 21:34:44 GMT+08:00 2021
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_person.name
     *
     * @param name the value for t_person.name
     *
     * @mbg.generated Fri Jul 30 21:34:44 GMT+08:00 2021
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }
}